services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_manager/alerts.yml:/etc/prometheus/alerts.yml
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    networks:
      - overlay
      - app_app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana  
      - GF_USERS_ALLOW_SIGN_UP=false 
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasources.yml 
      - source: grafana_dashboards_config
        target: /etc/grafana/provisioning/dashboards/dashboards.yml   
      - source: grafana_dashboard_json
        target: /etc/grafana/provisioning/dashboards/monitoring-dashboard.json
    networks:
      - overlay
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - overlay
    deploy:
      placement:
        constraints: [node.role == manager]

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - overlay
    deploy:
      mode: global

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - overlay
    deploy:
      mode: global

  blackbox_exporter: 
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    networks:
      - overlay

  cadvisor:  
    image: zcube/cadvisor:latest
    ports:
      - "8080:8080"
    deploy:
      mode: global
    networks:
      - overlay
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true

  # alertmanager:
  #   image: prom/alertmanager:latest
  #   volumes:
  #     - ./alert_manager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #   command:
  #     - --config.file=/etc/alertmanager/alertmanager.yml
  #   ports:
  #     - "9093:9093"
  #   networks:
  #     - overlay
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]

networks:
  overlay:
    external: true
    name: overlay
  app_app-network:
    external: true
    name: app_app-network

volumes:
  grafana-storage:

configs:
  grafana_datasources:
    file: ./datasources.yml
  grafana_dashboards_config:
    file: ./dashboards.yml
  grafana_dashboard_json:
    file: ./monitoring-dashboard.json