worker_processes 1;

events { worker_connections 1024; }

http {
    server {
        listen 8081;
        location / {
            proxy_pass http://session-service:8081;
        }
    }

    server {
        listen 8087;
        location / {
            proxy_pass http://gateway-service:8087;
        }
    }
}