version: '3.8'

services:
  twportainer:
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9443:9443"
    networks:
      - overlay
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

      - portainer_data:/data
    
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"

volumes:
  portainer_data:

networks:
  overlay:
    external: true