# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder ".", "/home/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  # Manager node
  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.network "forwarded_port", guest: 3000, host: 3000 # graphana 
    manager.vm.network "forwarded_port", guest: 3100, host: 3100 # loki
    manager.vm.network "forwarded_port", guest: 8080, host: 8080 # cadvisor
    manager.vm.network "forwarded_port", guest: 8081, host: 8081 # session
    manager.vm.network "forwarded_port", guest: 8087, host: 8087 # gateway
    manager.vm.network "forwarded_port", guest: 9090, host: 9090 # prometheus
    manager.vm.network "forwarded_port", guest: 9093, host: 9093 # alert
    manager.vm.network "forwarded_port", guest: 9100, host: 9100 # node-exporter
    manager.vm.network "forwarded_port", guest: 9115, host: 9115 # blackbox
    manager.vm.network "forwarded_port", guest: 9443, host: 9443 # portainer
    manager.vm.network "forwarded_port", guest: 15692, host: 15692 # rabbit
    manager.vm.provision "shell", path: "services/install_docker.sh"
    manager.vm.provision "shell", path: "services/manager.sh"
  end

  # Worker 1
  config.vm.define "worker01" do |worker|
    worker.vm.hostname = "worker01"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provision "shell", path: "services/install_docker.sh"
    worker.vm.provision "shell", path: "services/worker.sh"
  end

  # Worker 2
  config.vm.define "worker02" do |worker|
    worker.vm.hostname = "worker02"
    worker.vm.network "private_network", ip: "192.168.56.12"
    worker.vm.provision "shell", path: "services/install_docker.sh"
    worker.vm.provision "shell", path: "services/worker.sh"
  end

end